### ISSUE TITLE
Add an option not to fail on version mismatch

### ISSUE THREAD

**Issue by mayeut** [trailofbits/abi3audit#31]
As mentioned in the README:
> abi3audit considers the abi3 version when a symbol was stabilized, not introduced. In other words: abi3audit will produce a warning when an abi3-cp36 extension contains a function stabilized in 3.7, even if that function was introduced in 3.6. This is not a false positive (it is an ABI version mismatch), but it's generally not a source of bugs.

A symbol might become marked as ABI stable in 3.y but had its ABI unchanged since 3.x with x < y
While strictly speaking, this is an ABI3 version mismatch and hence, not a false positive, it would be nice to have the option not to return with exit code 1 for such mismatch.

> but it's generally not a source of bugs.

If the wheel are correctly tested, it will never be a source of bugs and allows a broader range of python versions to be supported with a single wheel.

**Comment by woodruffw** [comment]
Sorry, but I don't think we want support for this: CPython's maintainers can always retroactively specify an ABI member for older CPython versions, but it would be unsound in the general case for us to assume that stable ABI members were stable from their introduction version, rather than their stabilization version.

> If the wheel are correctly tested, it will never be a source of bugs and allows a broader range of python versions to be supported with a single wheel.

These things are difficult to correctly test, because they can involve undefined behavior: an ABI member might be "unchanged" before stabilization, but prior versions might not be `const`-correct or might have different parameter behavior, for example. The program as compiled might behave as expected, but that would be purely incidental and subject to changes to the compiler.

Out of curiosity: are you aware of people intentionally setting their ABI3 version lower than is correct, based on the assumption that the function's presence + similar parameters imply that it hasn't changed? I don't think that's a use case that I want to encourage 🙂
