### ISSUE TITLE
Potential false positive (compliant but flagged as non-compliant)

### ISSUE THREAD

**Issue by HendersonSC** [trailofbits/abi3audit#82]
Background: Wrapping a decently sized c++ utility library using Swig-4.2 (including its stable abi option) to generate python wrappers which subsequently provide features to user facing python classes. 

Tools: python 3.8.18 (via conda) and gcc 11.4.0 under Ubuntu22.04 on wsl 

```
% python -m abi3audit foo.whl -v --report
[11:18:59] 👎 foo.whl: _foo.cpython-38-x86_64-linux-gnu.so has non-ABI3 symbols
           ┏━━━━━━━━━━━━━┓
           ┃ Symbol      ┃
           ┡━━━━━━━━━━━━━┩
           │ _Py_XDECREF │
           └─────────────┘
           💁 foo-cp38-abi3-manylinux_2_34_x86_64.whl: 1 extensions scanned; 0 ABI version mismatches and 1 ABI violations found
  {"specs": {"wheelhouse/foo-cp38-abi3-manylinux_2_34_x86_64.whl": {"kind": "wheel", "wheel": [{"name": "_foo-38-x86_64-linux-gnu.so", "result": {"is_abi3": false, "is_abi3_baseline_compatible": true, "baseline": "3.8", "computed": "3.8", "non_abi3_sy
  mbols": ["_Py_XDECREF"], "future_abi3_objects": {}}}]}}}
```

From what I have read, which is hardly extensive, `Py_XDECREF` is a macro which expands to a non-null check and `Py_DECREF` which seems to have always been abi3.

Please forgive me if there is something I am misunderstanding about any part of this process, I have only recently jumped into wrapping an established code with python bindings and am filling in a lot of blanks on the fly. Any information on this would be appreciated.

**Comment by woodruffw** [comment]
To enumerate what *should* happen:

1. Some file in a C extension ends up including `object.h`, either directly or transitively
2. `object.h` contains the `Py_XDECREF` macro, which expands to a call to the `static inline _Py_XDECREF` helper.
3. *Normally*, the `static inline` function would be inlined and there would be no presence of `_Py_XDECREF` in the symbol table, either locally or globally.

What seems to be happening instead:

1. Rather than inlining `_Py_XDECREF`, the compiler appears to be making a `static` (i.e. local) copy of it in the translation unit, which then has a local-only symbol table entry.
2. `_Py_XDECREF` itself is definitely not in the stable ABI, so we flag it.
3. However, in practice, `_Py_XDECREF` is just an expansion of `_Py_DECREF` via `Py_DECREF`, which in turn has an entirely ABI3 compatible body (`_Py_NegativeRefcount` and `_Py_Dealloc` are both stable, despite having underscored names). So, *in practice*, any static copy of `_Py_XDECREF` should be stable ABI compatible.
4. *However*, this is an implementation detail. The static copy `_Py_XDECREF` *could* contain non-stable ABI references, e.g. making offset/pointer assumptions in CPython objects. It doesn't in 3.8, but there's nothing stopping it from doing so.

So, I think this is an ABI violation, full stop: it's probably not a dangerous one in Python 3.8, but we can't safety generalize that assumption for all non-stable `static` functions that get copied into translation units via `#include`.

**Comment by HendersonSC** [comment]
First, thank you for this incredibly detailed answer. Not much of what you elaborated on was apparent in the results I was getting.

So what this sounds like follows:

This is an ABI violation only because the compiler chose not to inline the function body at compile time. Had it done so, it would have only included things that are ABI compliant, eliding any reference to things that aren't "stable". This is indeed a fun little quirk, thank you for the information.

P.S. This is good information and explains why this particular warning did not come up on other distributions of this wheel.

**Comment by HendersonSC** [comment]
Linked to their issue board, in the meantime I am going to try out some options to see if I can avoid the problem in the near term.  Thanks agian!

**Comment by woodruffw** [comment]
No problem! Sent from mobile. Please excuse my brevity.On Mar 5, 2024, at 3:16 PM, HendersonSC ***@***.***> wrote:﻿
Linked to their issue board, in the meantime I am going to try out some options to see if I can avoid the problem in the near term.  Thanks agian!
